// AUTO-GENERATED by scripts/generate-content-manifest.js — do not edit by hand.
// Regenerate with: node scripts/generate-content-manifest.js

const img0 = require('../../assets/character/accessories/1.png');
const img1 = require('../../assets/character/accessories/2.png');
const img2 = require('../../assets/character/accessories/3.png');
const img3 = require('../../assets/character/accessories/4.png');
const img4 = require('../../assets/character/accessories/5.png');
const img5 = require('../../assets/character/accessories/6.png');
const img6 = require('../../assets/character/accessories/7.png');
const img7 = require('../../assets/character/accessories/8.png');
const img8 = require('../../assets/character/accessories/9.png');
const img9 = require('../../assets/character/accessories/10.png');
const img10 = require('../../assets/character/accessories/11.png');
const img11 = require('../../assets/character/accessories/13.png');
const img12 = require('../../assets/character/accessories/13b.png');
const img13 = require('../../assets/character/accessories/14.png');
const img14 = require('../../assets/character/accessories/15.png');
const img15 = require('../../assets/character/accessories/16.png');
const img16 = require('../../assets/character/accessories/16b.png');
const img17 = require('../../assets/character/accessories/17.png');
const img18 = require('../../assets/character/accessories/18.png');
const img19 = require('../../assets/character/accessories/19.png');
const img20 = require('../../assets/character/accessories/20.png');
const img21 = require('../../assets/character/accessories/21.png');
const img22 = require('../../assets/character/accessories/22.png');
const img23 = require('../../assets/character/accessories/23.png');
const img24 = require('../../assets/character/accessories/24.png');
const img25 = require('../../assets/character/accessories/25.png');
const img26 = require('../../assets/character/accessories/26.png');
const img27 = require('../../assets/character/accessories/27.png');
const img28 = require('../../assets/character/accessories/28.png');
const img29 = require('../../assets/character/accessories/29.png');
const img30 = require('../../assets/character/accessories/30.png');
const img31 = require('../../assets/character/accessories/31.png');
const img32 = require('../../assets/character/accessories/32.png');
const img33 = require('../../assets/character/accessories/33.png');
const img34 = require('../../assets/character/accessories/34.png');
const img35 = require('../../assets/character/accessories/35.png');
const img36 = require('../../assets/character/accessories/36.png');
const img37 = require('../../assets/character/accessories/37.png');
const img38 = require('../../assets/character/accessories/38.png');
const img39 = require('../../assets/character/accessories/39.png');
const img40 = require('../../assets/character/accessories/40.png');
const img41 = require('../../assets/character/accessories/41.png');
const img42 = require('../../assets/character/accessories/42.png');
const img43 = require('../../assets/character/accessories/43.png');
const img44 = require('../../assets/character/accessories/44.png');
const img45 = require('../../assets/character/accessories/45.png');
const img46 = require('../../assets/character/accessories/46.png');
const img47 = require('../../assets/character/accessories/47.png');
const img48 = require('../../assets/character/accessories/48.png');
const img49 = require('../../assets/character/accessories/49.png');
const img50 = require('../../assets/character/body_decor/1.png');
const img51 = require('../../assets/character/body_decor/2.png');
const img52 = require('../../assets/character/body_decor/3.png');
const img53 = require('../../assets/character/body_decor/4.png');
const img54 = require('../../assets/character/body_decor/5.png');
const img55 = require('../../assets/character/body_decor/6.png');
const img56 = require('../../assets/character/body_decor/7.png');
const img57 = require('../../assets/character/body_decor/8.png');
const img58 = require('../../assets/character/body_decor/9.png');
const img59 = require('../../assets/character/body_decor/10.png');
const img60 = require('../../assets/character/body_decor/11.png');
const img61 = require('../../assets/character/body_decor/12.png');
const img62 = require('../../assets/character/body_decor/13.png');
const img63 = require('../../assets/character/body_decor/14.png');
const img64 = require('../../assets/character/body_decor/15.png');
const img65 = require('../../assets/character/body_decor/16.png');
const img66 = require('../../assets/character/body_decor/17.png');
const img67 = require('../../assets/character/body_decor/18.png');
const img68 = require('../../assets/character/body_decor/19.png');
const img69 = require('../../assets/character/body_decor/20.png');
const img70 = require('../../assets/character/body_decor/21.png');
const img71 = require('../../assets/character/body_decor/22.png');
const img72 = require('../../assets/character/body_decor/23.png');
const img73 = require('../../assets/character/body_decor/24.png');
const img74 = require('../../assets/character/body_decor/25.png');
const img75 = require('../../assets/character/body_decor/26.png');
const img76 = require('../../assets/character/body_decor/27.png');
const img77 = require('../../assets/character/body_parts/1.png');
const img78 = require('../../assets/character/body_parts/2.png');
const img79 = require('../../assets/character/body_parts/3.png');
const img80 = require('../../assets/character/body_parts/4.png');
const img81 = require('../../assets/character/body_parts/5.png');
const img82 = require('../../assets/character/body_parts/6.png');
const img83 = require('../../assets/character/body_parts/7.png');
const img84 = require('../../assets/character/body_parts/8.png');
const img85 = require('../../assets/character/body_parts/9.png');
const img86 = require('../../assets/character/body_parts/10.png');
const img87 = require('../../assets/character/body_parts/11.png');
const img88 = require('../../assets/character/body_parts/12.png');
const img89 = require('../../assets/character/body_parts/13.png');
const img90 = require('../../assets/character/body_parts/14.png');
const img91 = require('../../assets/character/body_parts/15.png');
const img92 = require('../../assets/character/body_parts/16.png');
const img93 = require('../../assets/character/body_parts/17.png');
const img94 = require('../../assets/character/body_parts/18.png');
const img95 = require('../../assets/character/body_parts/19.png');
const img96 = require('../../assets/character/body_parts/20.png');
const img97 = require('../../assets/character/body_parts/21.png');
const img98 = require('../../assets/character/body_parts/22.png');
const img99 = require('../../assets/character/body_parts/23.png');
const img100 = require('../../assets/character/body_parts/24.png');
const img101 = require('../../assets/character/body_parts/25.png');
const img102 = require('../../assets/character/body_parts/26.png');
const img103 = require('../../assets/character/body_parts/27.png');
const img104 = require('../../assets/character/body_parts/28.png');
const img105 = require('../../assets/character/body_parts/29.png');
const img106 = require('../../assets/character/body_parts/30.png');
const img107 = require('../../assets/character/body_parts/31.png');
const img108 = require('../../assets/character/bottom/1.png');
const img109 = require('../../assets/character/bottom/2.png');
const img110 = require('../../assets/character/bottom/3.png');
const img111 = require('../../assets/character/bottom/4.png');
const img112 = require('../../assets/character/bottom/5.png');
const img113 = require('../../assets/character/bottom/6.png');
const img114 = require('../../assets/character/bottom/7.png');
const img115 = require('../../assets/character/bottom/8.png');
const img116 = require('../../assets/character/bottom/9.png');
const img117 = require('../../assets/character/bottom/10.png');
const img118 = require('../../assets/character/bottom/11.png');
const img119 = require('../../assets/character/bottom/12.png');
const img120 = require('../../assets/character/bottom/13.png');
const img121 = require('../../assets/character/decor_bg_front/1.png');
const img122 = require('../../assets/character/decor_bg_front/2.png');
const img123 = require('../../assets/character/decor_bg_front/3.png');
const img124 = require('../../assets/character/decor_bg_front/4.png');
const img125 = require('../../assets/character/decor_bg_front/5.png');
const img126 = require('../../assets/character/decor_bg_front/6.png');
const img127 = require('../../assets/character/decor_bg_front/7.png');
const img128 = require('../../assets/character/decor_bg_front/8.png');
const img129 = require('../../assets/character/decor_bg_front/9.png');
const img130 = require('../../assets/character/decor_bg_front/10.png');
const img131 = require('../../assets/character/decor_bg_front/11.png');
const img132 = require('../../assets/character/decor_bg_front/12.png');
const img133 = require('../../assets/character/decor_bg_front/13.png');
const img134 = require('../../assets/character/decor_bg_front/14.png');
const img135 = require('../../assets/character/decor_bg_front/15.png');
const img136 = require('../../assets/character/decor_bg_front/16.png');
const img137 = require('../../assets/character/decor_bg_front/17.png');
const img138 = require('../../assets/character/decor_bg_front/18.png');
const img139 = require('../../assets/character/decor_bg_front/19.png');
const img140 = require('../../assets/character/decor_bg_front/20.png');
const img141 = require('../../assets/character/decor_bg_front/21.png');
const img142 = require('../../assets/character/decor_bg_front/22.png');
const img143 = require('../../assets/character/decor_bg_front/23.png');
const img144 = require('../../assets/character/decor_bg_front/24.png');
const img145 = require('../../assets/character/decor_bg_front/25.png');
const img146 = require('../../assets/character/decor_bg_front/26.png');
const img147 = require('../../assets/character/decor_bg_front/27.png');
const img148 = require('../../assets/character/decor_bg_front/28.png');
const img149 = require('../../assets/character/decor_bg_front/29.png');
const img150 = require('../../assets/character/decor_bg_front/30.png');
const img151 = require('../../assets/character/decor_bg_front/31.png');
const img152 = require('../../assets/character/decor_bg_front/32.png');
const img153 = require('../../assets/character/decor_bg_front/33.png');
const img154 = require('../../assets/character/dress/1.png');
const img155 = require('../../assets/character/dress/2.png');
const img156 = require('../../assets/character/dress/3.png');
const img157 = require('../../assets/character/dress/3b.png');
const img158 = require('../../assets/character/dress/5.png');
const img159 = require('../../assets/character/face_items/1.png');
const img160 = require('../../assets/character/face_items/2.png');
const img161 = require('../../assets/character/face_items/3.png');
const img162 = require('../../assets/character/face_items/4.png');
const img163 = require('../../assets/character/face_items/5.png');
const img164 = require('../../assets/character/face_items/6.png');
const img165 = require('../../assets/character/face_items/7.png');
const img166 = require('../../assets/character/face_items/8.png');
const img167 = require('../../assets/character/face_items/9.png');
const img168 = require('../../assets/character/face_items/10.png');
const img169 = require('../../assets/character/face_items/11.png');
const img170 = require('../../assets/character/face_items/12.png');
const img171 = require('../../assets/character/face_items/13.png');
const img172 = require('../../assets/character/face_items/14.png');
const img173 = require('../../assets/character/face_items/15.png');
const img174 = require('../../assets/character/face_items/16.png');
const img175 = require('../../assets/character/face_items/17.png');
const img176 = require('../../assets/character/face_items/18.png');
const img177 = require('../../assets/character/face_items/19.png');
const img178 = require('../../assets/character/hand_weapons/1.png');
const img179 = require('../../assets/character/hand_weapons/2.png');
const img180 = require('../../assets/character/hand_weapons/3.png');
const img181 = require('../../assets/character/hand_weapons/4.png');
const img182 = require('../../assets/character/hand_weapons/5.png');
const img183 = require('../../assets/character/hand_weapons/6.png');
const img184 = require('../../assets/character/hand_weapons/7.png');
const img185 = require('../../assets/character/hand_weapons/8.png');
const img186 = require('../../assets/character/hand_weapons/9.png');
const img187 = require('../../assets/character/hand_weapons/10.png');
const img188 = require('../../assets/character/hand_weapons/11.png');
const img189 = require('../../assets/character/hand_weapons/12.png');
const img190 = require('../../assets/character/hand_weapons/13.png');
const img191 = require('../../assets/character/hand_weapons/14.png');
const img192 = require('../../assets/character/hand_weapons/15.png');
const img193 = require('../../assets/character/hand_weapons/16.png');
const img194 = require('../../assets/character/hand_weapons/17.png');
const img195 = require('../../assets/character/hand_weapons/18.png');
const img196 = require('../../assets/character/hand_weapons/19.png');
const img197 = require('../../assets/character/jacket/1.png');
const img198 = require('../../assets/character/jacket/2.png');
const img199 = require('../../assets/character/jacket/2b.png');
const img200 = require('../../assets/character/jacket/3.png');
const img201 = require('../../assets/character/jacket/4.png');
const img202 = require('../../assets/character/jacket/5.png');
const img203 = require('../../assets/character/jacket/6.png');
const img204 = require('../../assets/character/jacket/7.png');
const img205 = require('../../assets/character/jacket/8.png');
const img206 = require('../../assets/character/jacket/8b.png');
const img207 = require('../../assets/character/jacket/9.png');
const img208 = require('../../assets/character/jacket/9b.png');
const img209 = require('../../assets/character/jacket/10.png');
const img210 = require('../../assets/character/jacket/11.png');
const img211 = require('../../assets/character/jacket/12.png');
const img212 = require('../../assets/character/jacket/13.png');
const img213 = require('../../assets/character/jacket/13b.png');
const img214 = require('../../assets/character/shoes/1.png');
const img215 = require('../../assets/character/shoes/2.png');
const img216 = require('../../assets/character/shoes/3.png');
const img217 = require('../../assets/character/shoes/4.png');
const img218 = require('../../assets/character/shoes/5.png');
const img219 = require('../../assets/character/shoes/6.png');
const img220 = require('../../assets/character/shoes/7.png');
const img221 = require('../../assets/character/shoes/8.png');
const img222 = require('../../assets/character/shoes/9.png');
const img223 = require('../../assets/character/socks/1.png');
const img224 = require('../../assets/character/socks/2.png');
const img225 = require('../../assets/character/socks/3.png');
const img226 = require('../../assets/character/socks/4.png');
const img227 = require('../../assets/character/socks/5.png');
const img228 = require('../../assets/character/socks/6.png');
const img229 = require('../../assets/character/socks/7.png');
const img230 = require('../../assets/character/socks/8.png');
const img231 = require('../../assets/character/socks/9.png');
const img232 = require('../../assets/character/socks/10.png');
const img233 = require('../../assets/character/top/1.png');
const img234 = require('../../assets/character/top/2.png');
const img235 = require('../../assets/character/top/3.png');
const img236 = require('../../assets/character/top/4.png');
const img237 = require('../../assets/character/top/5.png');
const img238 = require('../../assets/character/top/6.png');
const img239 = require('../../assets/character/top/7.png');
const img240 = require('../../assets/character/top/8.png');
const img241 = require('../../assets/character/top/9.png');
const img242 = require('../../assets/character/top/10.png');
const img243 = require('../../assets/character/top/11.png');
const img244 = require('../../assets/character/top/12.png');
const img245 = require('../../assets/character/top/13.png');
const img246 = require('../../assets/character/top/14.png');
const img247 = require('../../assets/character/top/15.png');
const img248 = require('../../assets/character/top/16.png');
const img249 = require('../../assets/character/top/17.png');
const img250 = require('../../assets/character/top/18.png');
const img251 = require('../../assets/character/top/19.png');
const img252 = require('../../assets/character/top/20.png');
const img253 = require('../../assets/character/top_underwear/1.png');
const img254 = require('../../assets/character/top_underwear/2.png');
const img255 = require('../../assets/character/top_underwear/3.png');
const img256 = require('../../assets/character/top_underwear/4.png');
const img257 = require('../../assets/character/top_underwear/5.png');

export type ContentCategory = 'accessories' | 'body_decor' | 'body_parts' | 'bottom' | 'decor_bg_front' | 'dress' | 'face_items' | 'hand_weapons' | 'jacket' | 'shoes' | 'socks' | 'top' | 'top_underwear';

export interface ContentItem {
  id: string;
  category: ContentCategory;
  source: number;
}

export const CATEGORY_LABELS: Record<ContentCategory, string> = {
  accessories: 'Accessories',
  body_decor: 'Body Decor',
  body_parts: 'Body Parts',
  bottom: 'Bottoms',
  decor_bg_front: 'Scene Decor',
  dress: 'Dresses',
  face_items: 'Face Items',
  hand_weapons: 'Hand Items',
  jacket: 'Jackets',
  shoes: 'Shoes',
  socks: 'Socks',
  top: 'Tops',
  top_underwear: 'Top Underwear',
};

export const CONTENT_ITEMS: Record<ContentCategory, ContentItem[]> = {
  accessories: [
    { id: '1', category: 'accessories', source: img0 },
    { id: '2', category: 'accessories', source: img1 },
    { id: '3', category: 'accessories', source: img2 },
    { id: '4', category: 'accessories', source: img3 },
    { id: '5', category: 'accessories', source: img4 },
    { id: '6', category: 'accessories', source: img5 },
    { id: '7', category: 'accessories', source: img6 },
    { id: '8', category: 'accessories', source: img7 },
    { id: '9', category: 'accessories', source: img8 },
    { id: '10', category: 'accessories', source: img9 },
    { id: '11', category: 'accessories', source: img10 },
    { id: '13', category: 'accessories', source: img11 },
    { id: '13b', category: 'accessories', source: img12 },
    { id: '14', category: 'accessories', source: img13 },
    { id: '15', category: 'accessories', source: img14 },
    { id: '16', category: 'accessories', source: img15 },
    { id: '16b', category: 'accessories', source: img16 },
    { id: '17', category: 'accessories', source: img17 },
    { id: '18', category: 'accessories', source: img18 },
    { id: '19', category: 'accessories', source: img19 },
    { id: '20', category: 'accessories', source: img20 },
    { id: '21', category: 'accessories', source: img21 },
    { id: '22', category: 'accessories', source: img22 },
    { id: '23', category: 'accessories', source: img23 },
    { id: '24', category: 'accessories', source: img24 },
    { id: '25', category: 'accessories', source: img25 },
    { id: '26', category: 'accessories', source: img26 },
    { id: '27', category: 'accessories', source: img27 },
    { id: '28', category: 'accessories', source: img28 },
    { id: '29', category: 'accessories', source: img29 },
    { id: '30', category: 'accessories', source: img30 },
    { id: '31', category: 'accessories', source: img31 },
    { id: '32', category: 'accessories', source: img32 },
    { id: '33', category: 'accessories', source: img33 },
    { id: '34', category: 'accessories', source: img34 },
    { id: '35', category: 'accessories', source: img35 },
    { id: '36', category: 'accessories', source: img36 },
    { id: '37', category: 'accessories', source: img37 },
    { id: '38', category: 'accessories', source: img38 },
    { id: '39', category: 'accessories', source: img39 },
    { id: '40', category: 'accessories', source: img40 },
    { id: '41', category: 'accessories', source: img41 },
    { id: '42', category: 'accessories', source: img42 },
    { id: '43', category: 'accessories', source: img43 },
    { id: '44', category: 'accessories', source: img44 },
    { id: '45', category: 'accessories', source: img45 },
    { id: '46', category: 'accessories', source: img46 },
    { id: '47', category: 'accessories', source: img47 },
    { id: '48', category: 'accessories', source: img48 },
    { id: '49', category: 'accessories', source: img49 },
  ],
  body_decor: [
    { id: '1', category: 'body_decor', source: img50 },
    { id: '2', category: 'body_decor', source: img51 },
    { id: '3', category: 'body_decor', source: img52 },
    { id: '4', category: 'body_decor', source: img53 },
    { id: '5', category: 'body_decor', source: img54 },
    { id: '6', category: 'body_decor', source: img55 },
    { id: '7', category: 'body_decor', source: img56 },
    { id: '8', category: 'body_decor', source: img57 },
    { id: '9', category: 'body_decor', source: img58 },
    { id: '10', category: 'body_decor', source: img59 },
    { id: '11', category: 'body_decor', source: img60 },
    { id: '12', category: 'body_decor', source: img61 },
    { id: '13', category: 'body_decor', source: img62 },
    { id: '14', category: 'body_decor', source: img63 },
    { id: '15', category: 'body_decor', source: img64 },
    { id: '16', category: 'body_decor', source: img65 },
    { id: '17', category: 'body_decor', source: img66 },
    { id: '18', category: 'body_decor', source: img67 },
    { id: '19', category: 'body_decor', source: img68 },
    { id: '20', category: 'body_decor', source: img69 },
    { id: '21', category: 'body_decor', source: img70 },
    { id: '22', category: 'body_decor', source: img71 },
    { id: '23', category: 'body_decor', source: img72 },
    { id: '24', category: 'body_decor', source: img73 },
    { id: '25', category: 'body_decor', source: img74 },
    { id: '26', category: 'body_decor', source: img75 },
    { id: '27', category: 'body_decor', source: img76 },
  ],
  body_parts: [
    { id: '1', category: 'body_parts', source: img77 },
    { id: '2', category: 'body_parts', source: img78 },
    { id: '3', category: 'body_parts', source: img79 },
    { id: '4', category: 'body_parts', source: img80 },
    { id: '5', category: 'body_parts', source: img81 },
    { id: '6', category: 'body_parts', source: img82 },
    { id: '7', category: 'body_parts', source: img83 },
    { id: '8', category: 'body_parts', source: img84 },
    { id: '9', category: 'body_parts', source: img85 },
    { id: '10', category: 'body_parts', source: img86 },
    { id: '11', category: 'body_parts', source: img87 },
    { id: '12', category: 'body_parts', source: img88 },
    { id: '13', category: 'body_parts', source: img89 },
    { id: '14', category: 'body_parts', source: img90 },
    { id: '15', category: 'body_parts', source: img91 },
    { id: '16', category: 'body_parts', source: img92 },
    { id: '17', category: 'body_parts', source: img93 },
    { id: '18', category: 'body_parts', source: img94 },
    { id: '19', category: 'body_parts', source: img95 },
    { id: '20', category: 'body_parts', source: img96 },
    { id: '21', category: 'body_parts', source: img97 },
    { id: '22', category: 'body_parts', source: img98 },
    { id: '23', category: 'body_parts', source: img99 },
    { id: '24', category: 'body_parts', source: img100 },
    { id: '25', category: 'body_parts', source: img101 },
    { id: '26', category: 'body_parts', source: img102 },
    { id: '27', category: 'body_parts', source: img103 },
    { id: '28', category: 'body_parts', source: img104 },
    { id: '29', category: 'body_parts', source: img105 },
    { id: '30', category: 'body_parts', source: img106 },
    { id: '31', category: 'body_parts', source: img107 },
  ],
  bottom: [
    { id: '1', category: 'bottom', source: img108 },
    { id: '2', category: 'bottom', source: img109 },
    { id: '3', category: 'bottom', source: img110 },
    { id: '4', category: 'bottom', source: img111 },
    { id: '5', category: 'bottom', source: img112 },
    { id: '6', category: 'bottom', source: img113 },
    { id: '7', category: 'bottom', source: img114 },
    { id: '8', category: 'bottom', source: img115 },
    { id: '9', category: 'bottom', source: img116 },
    { id: '10', category: 'bottom', source: img117 },
    { id: '11', category: 'bottom', source: img118 },
    { id: '12', category: 'bottom', source: img119 },
    { id: '13', category: 'bottom', source: img120 },
  ],
  decor_bg_front: [
    { id: '1', category: 'decor_bg_front', source: img121 },
    { id: '2', category: 'decor_bg_front', source: img122 },
    { id: '3', category: 'decor_bg_front', source: img123 },
    { id: '4', category: 'decor_bg_front', source: img124 },
    { id: '5', category: 'decor_bg_front', source: img125 },
    { id: '6', category: 'decor_bg_front', source: img126 },
    { id: '7', category: 'decor_bg_front', source: img127 },
    { id: '8', category: 'decor_bg_front', source: img128 },
    { id: '9', category: 'decor_bg_front', source: img129 },
    { id: '10', category: 'decor_bg_front', source: img130 },
    { id: '11', category: 'decor_bg_front', source: img131 },
    { id: '12', category: 'decor_bg_front', source: img132 },
    { id: '13', category: 'decor_bg_front', source: img133 },
    { id: '14', category: 'decor_bg_front', source: img134 },
    { id: '15', category: 'decor_bg_front', source: img135 },
    { id: '16', category: 'decor_bg_front', source: img136 },
    { id: '17', category: 'decor_bg_front', source: img137 },
    { id: '18', category: 'decor_bg_front', source: img138 },
    { id: '19', category: 'decor_bg_front', source: img139 },
    { id: '20', category: 'decor_bg_front', source: img140 },
    { id: '21', category: 'decor_bg_front', source: img141 },
    { id: '22', category: 'decor_bg_front', source: img142 },
    { id: '23', category: 'decor_bg_front', source: img143 },
    { id: '24', category: 'decor_bg_front', source: img144 },
    { id: '25', category: 'decor_bg_front', source: img145 },
    { id: '26', category: 'decor_bg_front', source: img146 },
    { id: '27', category: 'decor_bg_front', source: img147 },
    { id: '28', category: 'decor_bg_front', source: img148 },
    { id: '29', category: 'decor_bg_front', source: img149 },
    { id: '30', category: 'decor_bg_front', source: img150 },
    { id: '31', category: 'decor_bg_front', source: img151 },
    { id: '32', category: 'decor_bg_front', source: img152 },
    { id: '33', category: 'decor_bg_front', source: img153 },
  ],
  dress: [
    { id: '1', category: 'dress', source: img154 },
    { id: '2', category: 'dress', source: img155 },
    { id: '3', category: 'dress', source: img156 },
    { id: '3b', category: 'dress', source: img157 },
    { id: '5', category: 'dress', source: img158 },
  ],
  face_items: [
    { id: '1', category: 'face_items', source: img159 },
    { id: '2', category: 'face_items', source: img160 },
    { id: '3', category: 'face_items', source: img161 },
    { id: '4', category: 'face_items', source: img162 },
    { id: '5', category: 'face_items', source: img163 },
    { id: '6', category: 'face_items', source: img164 },
    { id: '7', category: 'face_items', source: img165 },
    { id: '8', category: 'face_items', source: img166 },
    { id: '9', category: 'face_items', source: img167 },
    { id: '10', category: 'face_items', source: img168 },
    { id: '11', category: 'face_items', source: img169 },
    { id: '12', category: 'face_items', source: img170 },
    { id: '13', category: 'face_items', source: img171 },
    { id: '14', category: 'face_items', source: img172 },
    { id: '15', category: 'face_items', source: img173 },
    { id: '16', category: 'face_items', source: img174 },
    { id: '17', category: 'face_items', source: img175 },
    { id: '18', category: 'face_items', source: img176 },
    { id: '19', category: 'face_items', source: img177 },
  ],
  hand_weapons: [
    { id: '1', category: 'hand_weapons', source: img178 },
    { id: '2', category: 'hand_weapons', source: img179 },
    { id: '3', category: 'hand_weapons', source: img180 },
    { id: '4', category: 'hand_weapons', source: img181 },
    { id: '5', category: 'hand_weapons', source: img182 },
    { id: '6', category: 'hand_weapons', source: img183 },
    { id: '7', category: 'hand_weapons', source: img184 },
    { id: '8', category: 'hand_weapons', source: img185 },
    { id: '9', category: 'hand_weapons', source: img186 },
    { id: '10', category: 'hand_weapons', source: img187 },
    { id: '11', category: 'hand_weapons', source: img188 },
    { id: '12', category: 'hand_weapons', source: img189 },
    { id: '13', category: 'hand_weapons', source: img190 },
    { id: '14', category: 'hand_weapons', source: img191 },
    { id: '15', category: 'hand_weapons', source: img192 },
    { id: '16', category: 'hand_weapons', source: img193 },
    { id: '17', category: 'hand_weapons', source: img194 },
    { id: '18', category: 'hand_weapons', source: img195 },
    { id: '19', category: 'hand_weapons', source: img196 },
  ],
  jacket: [
    { id: '1', category: 'jacket', source: img197 },
    { id: '2', category: 'jacket', source: img198 },
    { id: '2b', category: 'jacket', source: img199 },
    { id: '3', category: 'jacket', source: img200 },
    { id: '4', category: 'jacket', source: img201 },
    { id: '5', category: 'jacket', source: img202 },
    { id: '6', category: 'jacket', source: img203 },
    { id: '7', category: 'jacket', source: img204 },
    { id: '8', category: 'jacket', source: img205 },
    { id: '8b', category: 'jacket', source: img206 },
    { id: '9', category: 'jacket', source: img207 },
    { id: '9b', category: 'jacket', source: img208 },
    { id: '10', category: 'jacket', source: img209 },
    { id: '11', category: 'jacket', source: img210 },
    { id: '12', category: 'jacket', source: img211 },
    { id: '13', category: 'jacket', source: img212 },
    { id: '13b', category: 'jacket', source: img213 },
  ],
  shoes: [
    { id: '1', category: 'shoes', source: img214 },
    { id: '2', category: 'shoes', source: img215 },
    { id: '3', category: 'shoes', source: img216 },
    { id: '4', category: 'shoes', source: img217 },
    { id: '5', category: 'shoes', source: img218 },
    { id: '6', category: 'shoes', source: img219 },
    { id: '7', category: 'shoes', source: img220 },
    { id: '8', category: 'shoes', source: img221 },
    { id: '9', category: 'shoes', source: img222 },
  ],
  socks: [
    { id: '1', category: 'socks', source: img223 },
    { id: '2', category: 'socks', source: img224 },
    { id: '3', category: 'socks', source: img225 },
    { id: '4', category: 'socks', source: img226 },
    { id: '5', category: 'socks', source: img227 },
    { id: '6', category: 'socks', source: img228 },
    { id: '7', category: 'socks', source: img229 },
    { id: '8', category: 'socks', source: img230 },
    { id: '9', category: 'socks', source: img231 },
    { id: '10', category: 'socks', source: img232 },
  ],
  top: [
    { id: '1', category: 'top', source: img233 },
    { id: '2', category: 'top', source: img234 },
    { id: '3', category: 'top', source: img235 },
    { id: '4', category: 'top', source: img236 },
    { id: '5', category: 'top', source: img237 },
    { id: '6', category: 'top', source: img238 },
    { id: '7', category: 'top', source: img239 },
    { id: '8', category: 'top', source: img240 },
    { id: '9', category: 'top', source: img241 },
    { id: '10', category: 'top', source: img242 },
    { id: '11', category: 'top', source: img243 },
    { id: '12', category: 'top', source: img244 },
    { id: '13', category: 'top', source: img245 },
    { id: '14', category: 'top', source: img246 },
    { id: '15', category: 'top', source: img247 },
    { id: '16', category: 'top', source: img248 },
    { id: '17', category: 'top', source: img249 },
    { id: '18', category: 'top', source: img250 },
    { id: '19', category: 'top', source: img251 },
    { id: '20', category: 'top', source: img252 },
  ],
  top_underwear: [
    { id: '1', category: 'top_underwear', source: img253 },
    { id: '2', category: 'top_underwear', source: img254 },
    { id: '3', category: 'top_underwear', source: img255 },
    { id: '4', category: 'top_underwear', source: img256 },
    { id: '5', category: 'top_underwear', source: img257 },
  ],
};

export const CONTENT_CANVAS_WIDTH = 800;
export const CONTENT_CANVAS_HEIGHT = 1200;
